### ISSUE TITLE
No log files found in the logging directory of docker container running on Apple M1

### ISSUE THREAD

**Issue by subhod-i** [aeternity/aepp-sdk-js#1326]
**Describe the bug**
While debugging on why node fails to start up, wanted to have a look at the debug logs but the /home/aeternity/node/log directory is empty.

**To Reproduce**
1.  Set the logging to debug
```yml
logging:
    # Controls the overload protection in the logs.
    hwm: 50
    # Sets the level of logging.
    level: debug
```
2. docker-compose up -d
3. docker exec -it *** bash
4. ls log

**Expected behavior**
Logging directory with different logging files

**Please tell us about your environment:**

  - docker version : v20.10.10
  - docker-compose verison: v2.1.1
  - branch: develop
  - OS: M1 Pro Apple Silicon running **docker on rosetta 2**
